package com.arkadiusz.migala.simplecrud;

import com.arkadiusz.migala.simplecrud.controller.ArticleController;
import io.restassured.module.mockmvc.RestAssuredMockMvc;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

/**
 * Contract test generated by generateTests mvn job
 * should be available on target
 * they are prepared with contract *.groovy and runned
 * with rest assured mock
 */
@RunWith(SpringRunner.class)
@SpringBootTest
public class ContractTestBase {

    @Test
    public void contextLoads() {
    }

    @Autowired
    private ArticleController articleController;

    @Before
    public void setUp() {
        RestAssuredMockMvc.standaloneSetup(articleController);
    }

}
